name: MCCowsay
main: littlegruz.cowsay.CowsayMain
version: 0.1
platform: SERVER
author: LittleGruz

commands:
   cowsay:
      description: Displays an ASCII cow with the users message
      usage: /cowsay ['h'] [type] <message>
permissions:
   mccowsay.cowsay:
      description: Displays an ASCII cow with the users message
      default: op