name: MCCowsay
main: littlegruz.cowsay.MCCowsay
version: 1.8
commands:
   cowsay:
      description: Displays an ASCII cow with the users message
      usage: /cowsay ['h'] [type] <message>
   cowsaycows:
      description: Lists the available cows
      usage: /cowsaycows
   cowkillsay:
      description: Toggles the appearance of a cowsay message on cow death
      usage: /cowkillsay
   cowsaycooldown:
      description: Sets the cooldown time between cowsay command calls
      usage: /cowsaycooldown <time_in_sec>
permissions:
   mccowsay.cowsay:
      description: Displays an ASCII cow with the users message
      default: op
   mccowsay.cowsaycows:
      description: Lists the available cows
      default: op
   mccowsay.cowkillsay:
      description: Toggles the appearance of a cowsay message on cow death
      default: op
   mccowsay.cooldown:
      description: Sets the cooldown time between cowsay command calls
      default: op